# AmsterdamUMCdb Concept table Exploration

## Objectives
- Search the concept table for ventilation, ECMO, and candidate feature terms.
- Validate each concept against the data by visit/row counts.
- Using the concept_ancestor hierarchy to find concepts a keyword search misses.
- Confirm which domain each concept lives in(Procedure, Measurement, etc.)
- Output a validated concept list for the cohort and feature notebooks.

### Imports

In [1]:
import pandas as pd
import numpy as np
from google.cloud import bigquery
import matplotlib.pyplot as plt

Initial BigQuery Setup by Ayushi Kashyap - Adapted for this notebook.

### Retrieving Google Project Id

In [2]:
client = bigquery.Client()

print("Connected to BigQuery")

Connected to BigQuery

In [3]:
# sets *your* project id
PROJECT_ID = "capstoneweaningprediction" #@param {type:"string"}

# Sets the default BigQuery dataset for accessing AmsterdamUMCdb

If you have received instructions to use a specific BigQuery instance, change the default settings here. Otherwise use these default values.

In [4]:
# sets default dataset for AmsterdamUMCdb
DATASET_PROJECT_ID = 'amsterdamumcdb' #@param {type:"string"}
DATASET_ID = 'version1_5_0' #@param {type:"string"}
LOCATION = 'eu' #@param {type:"string"}

# Provide your credentials to access the AmsterdamUMCdb dataset on Google BigQuery
Authenticate your credentials with Google Cloud Platform and set your default Google Cloud Project ID as an environment variable for running query jobs.

1. Run the cell. The `Allow this notebook to access your Google credentials?` prompt appears. Select `Allow`.
2. In the `Sign in - Google Accounts` dialog, use the account you registered during the AmsterdamUMCdb application process and select `Allow` again.

In [5]:
import os
from google.colab import auth

# all libraries check this environment variable, so set it:
os.environ["GOOGLE_CLOUD_PROJECT"] = PROJECT_ID

auth.authenticate_user()
print('Authenticated')

Authenticated

# Enable data table display

Colab includes the `google.colab.data_table` package that can be used to display Pandas dataframes as an interactive data table (default limits: `max_rows = 20000`, `max_columns = 20`). This is especially useful when exploring the  tables or dictionary from AmsterdamUMCdb. It can be enabled with:

In [6]:
%load_ext google.colab.data_table
from google.colab.data_table import DataTable

# change default limits:
DataTable.max_columns = 50
DataTable.max_rows = 80000


## Set the default query job configuration for magics

In [7]:
%load_ext bigquery_magics
from bigquery_magics import bigquery_magics
from google.cloud import bigquery

# sets the default query job configuration
def_config = bigquery.job.QueryJobConfig(default_dataset=DATASET_PROJECT_ID + "." + DATASET_ID)
bigquery_magics.context.default_query_job_config = def_config

## Query the `person` table and copy the data to the `persons` Pandas dataframe:

The `person` table contains a record for each patient in AmsterdamUMCdb.

Since this is a relatively small table, it is acceptable to use `SELECT *`.

**Note**: Should an error occur while running the query, please see
the AmsterdamUMCdb BigQuery [Frequently Asked Questions](https://github.com/AmsterdamUMC/AmsterdamUMCdb/wiki/bigquery#faq).

In [8]:
%%bigquery person
SELECT * FROM `amsterdamumcdb.version1_5_0.person`;

Query is running:   0%|          |

Downloading:   0%|          |


## Set the default query job configuration for google-cloud-bigquery client

In [9]:
from google.cloud import bigquery

# BigQuery requires a separate config to prevent the 'BadRequest: 400 Cannot explicitly modify anonymous table' error message
job_config = bigquery.job.QueryJobConfig()

# sets default client settings by re-using the previously defined config
client = bigquery.Client(project=PROJECT_ID, location=LOCATION, default_query_job_config=def_config)

### Explore Concept Table

In [10]:
query = f"""
SELECT *
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
"""

concept_df = client.query(query).to_dataframe()

concept_df.head()

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,2617621,CLINICIAN DOCUMENTED THAT PROPHYLACTIC ANTIBIO...,Observation,HCPCS,HCPCS,S,G8211,1970-01-01,2011-10-30,None
1,2617574,Patient documented as being treated with antid...,Observation,HCPCS,HCPCS,S,G8129,1970-01-01,2014-11-11,None
2,2721144,UTERINE ARTERY EMBOLIZATION FOR UTERINE FIBROI...,Procedure,HCPCS,HCPCS,S,S2250,1970-01-01,2011-10-30,None
3,2720703,"ALS VEHICLE USED, NON-EMERGENCY TRANSPORT, NO ...",Observation,HCPCS,HCPCS,None,Q3020,1970-01-01,2011-01-09,None
4,2617676,Patient not documented to have received plan o...,Observation,HCPCS,HCPCS,S,G8268,1970-01-01,2014-11-11,None

#### Explore Domain Distribution

In [11]:
query = f"""
SELECT domain_id, COUNT(*) AS count
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
GROUP BY domain_id
ORDER BY count DESC
"""

concept_domain_df = client.query(query).to_dataframe()

concept_domain_df

              domain_id    count
0                  Drug  4620617
1           Observation   378247
2             Condition   258368
3                Device   236567
4             Geography   204035
5           Measurement   186645
6             Procedure    99306
7    Spec Anatomic Site    40148
8            Meas Value    25187
9              Metadata     4759
10                 Note     4071
11         Type Concept     3758
12                 Unit     2478
13             Specimen     2062
14             Provider     1552
15             Language      875
16                Visit      714
17                 Race      571
18         Revenue Code      545
19         Relationship      418
20                Route      217
21             Currency      180
22                Payer      168
23                 Cost       51
24     Condition Status       22
25              Episode       18
26               Gender       15
27     Plan Stop Reason       13
28                 Plan       11
29       Condition/Meas        8
30  Meas Value Operator        7
31              Sponsor        6
32            Ethnicity        2
33     Condition/Device        1

Measurement, Device, and Procedure are well represented in the database.

#### Explore Vocabulary Distribution

In [12]:
query = f"""
SELECT vocabulary_id, COUNT(*) AS count
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
GROUP BY vocabulary_id
ORDER BY count DESC
"""

concept_vocabulary_df = client.query(query).to_dataframe()

concept_vocabulary_df

           vocabulary_id    count
0       RxNorm Extension  2145325
1                    NDC  1195711
2                 SNOMED  1079403
3                    SPL   721549
4                 RxNorm   308709
5                  LOINC   269552
6                    OSM   203339
7                ICD10CM    99130
8                 ICD9CM    17564
9                  HCPCS    11948
10                   ATC     6740
11              ICD9Proc     4657
12        OMOP Extension     1444
13                  UCUM     1120
14                   CDM     1060
15                  NUCC      855
16          Relationship      718
17          Revenue Code      538
18         Concept Class      423
19         UB04 Typ bill      298
20              Currency      180
21                  SOPT      168
22            Vocabulary      148
23    Medicare Specialty      120
24        Condition Type      118
25                  ABMS       98
26        Procedure Type       97
27          Type Concept       80
28                Domain       65
29  CMS Place of Service       60
30    UB04 Pt dis status       55
31                  Race       53
32                  Cost       51
33      Observation Type       29
34  UB04 Point of Origin       23
35      Condition Status       22
36                 Visit       19
37               Episode       18
38            Visit Type       18
39             Drug Type       16
40            Death Type       14
41      Plan Stop Reason       13
42             US Census       13
43             Meas Type       12
44                  Plan       11
45             Note Type       10
46             Cost Type        8
47   Korean Revenue Code        7
48       Obs Period Type        6
49   UB04 Pri Typ of Adm        6
50               Sponsor        6
51                Gender        5
52           Device Type        4
53             Ethnicity        2
54              Metadata        2
55              Language        1
56                  None        1

RxNorm Extension and RxNorm together dominate the vocabulary

#### Search Ventilation Concepts

In [13]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE Lower(concept_name) LIKE '%ventilation%'
"""

ventilation_concept_df = client.query(query).to_dataframe()

ventilation_concept_df

,concept_id,concept_name,domain_id
0,43021811,Sleep related hypoventilation or hypoxemia,Condition
1,42530690,Invasive mechanical ventilation by intubation ...,Meas Value
2,42527120,Expired minute Volume during Mechanical ventil...,Measurement
3,42527121,Inspired minute Volume during Mechanical venti...,Measurement
4,42535241,Dependence on biphasic positive airway pressur...,Observation
...,...,...,...
475,4266619,Ventilation detail,Measurement
476,4229907,"Assisted ventilation therapy, pressure or volu...",Procedure
477,4283075,"Flow and timed ventilation procedure, initiati...",Procedure
478,4164571,Positive end expiratory pressure ventilation t...,Procedure
479,4097246,"Controlled ventilation procedure and therapy, ...",Procedure

### Ventillation Concepts With Count

 AI-assisted (Claude, Anthropic — Claude Opus 4.8): ventilation-concept search with visit-count validation drafted with AI.

In [14]:
query = f"""
SELECT
    c.concept_id,
    c.concept_name,
    c.domain_id,
    COUNT(DISTINCT po.visit_occurrence_id) AS visit_count
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept` c
LEFT JOIN `{DATASET_PROJECT_ID}.{DATASET_ID}.procedure_occurrence` po
       ON po.procedure_concept_id = c.concept_id
      AND po.provider_id IS NOT NULL
WHERE LOWER(c.concept_name) LIKE '%ventilation%'
GROUP BY c.concept_id, c.concept_name, c.domain_id
ORDER BY visit_count DESC
"""
ventilation_concept_df = client.query(query).to_dataframe()
print(f"Concepts matching 'ventilation': {len(ventilation_concept_df)}")
print(f"With data in procedure_occurrence: {(ventilation_concept_df['visit_count'] > 0).sum()}")
ventilation_concept_df

Concepts matching 'ventilation': 480
With data in procedure_occurrence: 14

,concept_id,concept_name,domain_id,visit_count
0,37154096,Pressure support ventilation,Procedure,14528
1,37151337,Continuous mandatory ventilation pressure-cont...,Procedure,14276
2,37152413,Continuous mandatory ventilation volume-contro...,Procedure,6046
3,40486624,Non-invasive positive pressure ventilation,Procedure,2012
4,4165535,Continuous positive airway pressure ventilatio...,Procedure,915
...,...,...,...,...
475,1026399,Views ventilation and perfusion,Observation,0
476,1024805,Multisection ventilation+perfusion^W radionucl...,Observation,0
477,1024609,Voluntary ventilation.max^pre bronchodilator/V...,Observation,0
478,1024407,Breaths^at maximum voluntary ventilation,Observation,0
479,4057263,Intermittent positive pressure ventilation,Procedure,0

#### Search Extubation Concepts

In [15]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE Lower(concept_name) LIKE '%extubation%'
"""

extubation_concept_df = client.query(query).to_dataframe()

extubation_concept_df

    concept_id                                       concept_name    domain_id
0     45882213                               Unplanned extubation   Meas Value
1      3657545        Recently performed an extubation of trachea  Observation
2      3040451                                 Extubation urgency  Observation
3     36304219                                 Time of extubation  Observation
4     42537924  Accidental awareness under general anesthesia ...  Observation
5      1027261                                 Extubation urgency  Observation
6     37049773                                 Time of extubation  Observation
7     37055966  Time of extubation | Patient | Respiratory mea...  Observation
8     37399087  Post extubation acute respiratory failure requ...    Condition
9     40378383      Extubation (& [removal of endotracheal tube])    Procedure
10     4337736                             Extubation of bronchus    Procedure
11     4148972                              Extubation of trachea    Procedure
12     4124035               Extubation of gastrointestinal tract    Procedure
13     4231838                    Inadvertent tracheal extubation  Observation
14     4236712                Difficulty with tracheal extubation  Observation

Extubation Concepts Count

AI-assisted (Claude, Anthropic — Claude Opus 4.8): extubation-concept search with multi-table visit-count validation drafted with AI.

In [16]:
query = f"""
WITH ext AS (
    SELECT concept_id, concept_name, domain_id
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
    WHERE LOWER(concept_name) LIKE '%extubation%'
)
SELECT
    e.concept_id,
    e.concept_name,
    e.domain_id,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.procedure_occurrence`
      WHERE procedure_concept_id = e.concept_id AND provider_id IS NOT NULL)  AS proc_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.observation`
      WHERE observation_concept_id = e.concept_id AND provider_id IS NOT NULL) AS obs_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
      WHERE measurement_concept_id = e.concept_id AND provider_id IS NOT NULL) AS meas_visits
FROM ext e
ORDER BY proc_visits DESC, obs_visits DESC, meas_visits DESC
"""
extubation_concept_df = client.query(query).to_dataframe()
extubation_concept_df['total_visits'] = extubation_concept_df[['proc_visits','obs_visits','meas_visits']].sum(axis=1)
print(f"Concepts matching 'extubation': {len(extubation_concept_df)}")
print(f"With any data: {(extubation_concept_df['total_visits'] > 0).sum()}")
extubation_concept_df

Concepts matching 'extubation': 15
With any data: 0

,concept_id,concept_name,domain_id,proc_visits,obs_visits,meas_visits,total_visits
0,42537924,Accidental awareness under general anesthesia ...,Observation,0,0,0,0
1,4231838,Inadvertent tracheal extubation,Observation,0,0,0,0
2,4337736,Extubation of bronchus,Procedure,0,0,0,0
3,1027261,Extubation urgency,Observation,0,0,0,0
4,4236712,Difficulty with tracheal extubation,Observation,0,0,0,0
5,4124035,Extubation of gastrointestinal tract,Procedure,0,0,0,0
6,37055966,Time of extubation | Patient | Respiratory mea...,Observation,0,0,0,0
7,4148972,Extubation of trachea,Procedure,0,0,0,0
8,36304219,Time of extubation,Observation,0,0,0,0
9,37399087,Post extubation acute respiratory failure requ...,Condition,0,0,0,0
10,40378383,Extubation (& [removal of endotracheal tube]),Procedure,0,0,0,0
11,37049773,Time of extubation,Observation,0,0,0,0
12,45882213,Unplanned extubation,Meas Value,0,0,0,0
13,3040451,Extubation urgency,Observation,0,0,0,0
14,3657545,Recently performed an extubation of trachea,Observation,0,0,0,0

#### Search Intubation Concepts

In [17]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE concept_name LIKE '%intubation%'
"""

intubation_concept_df = client.query(query).to_dataframe()

intubation_concept_df

,concept_id,concept_name,domain_id
0,42530690,Invasive mechanical ventilation by intubation ...,Meas Value
1,42536231,Video intubation laryngoscope kit,Device
2,42536230,Video intubation laryngoscope handle/monitor,Device
3,42536219,Video intubation laryngoscope blade,Device
4,42537975,"Rigid intubation laryngoscope, single-use",Device
...,...,...,...
148,4175851,History of difficult intubation,Observation
149,4176465,History of intubation of gastrointestinal trac...,Observation
150,4134538,Unintended endobronchial intubation,Procedure
151,4160174,Inadvertent esophageal intubation,Procedure
152,4162365,Failed intubation,Observation

### Intubation Visit Count

In [18]:
query = f"""
WITH intub AS (
    SELECT concept_id, concept_name, domain_id
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
    WHERE LOWER(concept_name) LIKE '%intubation%'
)
SELECT
    i.concept_id,
    i.concept_name,
    i.domain_id,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.procedure_occurrence`
      WHERE procedure_concept_id = i.concept_id AND provider_id IS NOT NULL)  AS proc_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.observation`
      WHERE observation_concept_id = i.concept_id AND provider_id IS NOT NULL) AS obs_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
      WHERE measurement_concept_id = i.concept_id AND provider_id IS NOT NULL) AS meas_visits
FROM intub i
ORDER BY proc_visits DESC, obs_visits DESC, meas_visits DESC
"""
intubation_concept_df = client.query(query).to_dataframe()
intubation_concept_df['total_visits'] = intubation_concept_df[['proc_visits','obs_visits','meas_visits']].sum(axis=1)
print(f"Concepts matching 'intubation': {len(intubation_concept_df)}")
print(f"With any data: {(intubation_concept_df['total_visits'] > 0).sum()}")
intubation_concept_df

Concepts matching 'intubation': 276
With any data: 3

,concept_id,concept_name,domain_id,proc_visits,obs_visits,meas_visits,total_visits
0,4202832,Intubation,Procedure,1035,0,0,1035
1,3046004,Intubation tube depth Respiratory system,Measurement,0,0,9171,9171
2,3028878,Tube cuff pressure Intubation tube,Measurement,0,0,5566,5566
3,4123572,Intubation of gastrointestinal tract via colos...,Procedure,0,0,0,0
4,1761298,COVID-19 Intubation Progress note | Hospital |...,Note,0,0,0,0
...,...,...,...,...,...,...,...
271,37159176,At increased risk for difficult tracheal intub...,Observation,0,0,0,0
272,3544483,Intubation of rectum,Procedure,0,0,0,0
273,3566295,Digital assisted intubation,Procedure,0,0,0,0
274,4066650,Intubation of jejunum for measurement of intes...,Procedure,0,0,0,0
275,715269,COVID-19 Intubation and Cardiopulmonary resusc...,Note,0,0,0,0

### Identify Respiratory Measurements

In [19]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE lower(concept_name) LIKE '%respiratory%'
"""

respiratory_concept_df = client.query(query).to_dataframe()

respiratory_concept_df

,concept_id,concept_name,domain_id
0,46238011,Functions of the respiratory system,Meas Value
1,46237196,Medical-Respiratory Distress-Bronchiolitis,Meas Value
2,46237640,Medical-Respiratory Distress-Croup,Meas Value
3,46237772,"Structures of the cardiovascular, immunologica...",Meas Value
4,46366214,budesonide .25mg/2mL RESPIRATORY (INHALATION) ...,Drug
...,...,...,...
18068,36142172,oxygen 99L/100L RESPIRATORY (INHALATION) GAS,Drug
18069,36378163,oxygen 99L/100L RESPIRATORY (INHALATION) GAS,Drug
18070,35908222,oxygen 99L/100L RESPIRATORY (INHALATION) GAS,Drug
18071,36335412,oxygen 99L/100L RESPIRATORY (INHALATION) GAS,Drug
18072,36464574,oxygen 99L/100L RESPIRATORY (INHALATION) GAS,Drug

### Respiratory concepts visit count

In [20]:
query = f"""
WITH resp AS (
    SELECT concept_id, concept_name, domain_id
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
    WHERE LOWER(concept_name) LIKE '%respiratory%'
)
SELECT
    r.concept_id,
    r.concept_name,
    r.domain_id,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
      WHERE measurement_concept_id = r.concept_id AND provider_id IS NOT NULL) AS meas_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.procedure_occurrence`
      WHERE procedure_concept_id = r.concept_id AND provider_id IS NOT NULL)  AS proc_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.observation`
      WHERE observation_concept_id = r.concept_id AND provider_id IS NOT NULL) AS obs_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.condition_occurrence`
      WHERE condition_concept_id = r.concept_id AND provider_id IS NOT NULL) AS cond_visits
FROM resp r
ORDER BY meas_visits DESC, proc_visits DESC, obs_visits DESC, cond_visits DESC
"""
respiratory_concept_df = client.query(query).to_dataframe()
respiratory_concept_df['total_visits'] = respiratory_concept_df[['meas_visits','proc_visits','obs_visits','cond_visits']].sum(axis=1)
print(f"Concepts matching 'respiratory': {len(respiratory_concept_df)}")
print(f"With any data: {(respiratory_concept_df['total_visits'] > 0).sum()}")
respiratory_concept_df.head(40)

Concepts matching 'respiratory': 18073
With any data: 48

,concept_id,concept_name,domain_id,meas_visits,proc_visits,obs_visits,cond_visits,total_visits
0,3024171,Respiratory rate,Measurement,21962,0,0,0,21962
1,3016078,Maximum [Pressure] Respiratory system airway o...,Measurement,16437,0,0,0,16437
2,21490855,PEEP Respiratory system --on ventilator,Measurement,16431,0,0,0,16431
3,3025408,Oxygen/Inspired gas Respiratory system by O2 A...,Measurement,15694,0,0,0,15694
4,3015016,Tidal volume expired spontaneous+mechanical Re...,Measurement,15527,0,0,0,15527
5,21490580,Carbon dioxide production (VCO2) in Respirator...,Measurement,13272,0,0,0,13272
6,3046004,Intubation tube depth Respiratory system,Measurement,9171,0,0,0,9171
7,21490737,Airway pressure --during respiratory pause,Measurement,6409,0,0,0,6409
8,42527140,Total PEEP Respiratory system,Measurement,1774,0,0,0,1774
9,21490789,Tidal volume expired Respiratory system airway...,Measurement,942,0,0,0,942
10,3035822,Intrinsic PEEP Respiratory system,Measurement,148,0,0,0,148
11,36305681,Parainfluenza virus 1 RNA [Presence] in Lower ...,Measurement,137,0,0,0,137
12,1176113,Human metapneumovirus RNA [Presence] in Lower ...,Measurement,137,0,0,0,137
13,36304298,Parainfluenza virus 4 RNA [Presence] in Lower ...,Measurement,137,0,0,0,137
14,36303784,Parainfluenza virus 3 RNA [Presence] in Lower ...,Measurement,137,0,0,0,137
15,36304319,Parainfluenza virus 2 RNA [Presence] in Lower ...,Measurement,137,0,0,0,137
16,46235767,Respiratory syncytial virus RNA [Presence] in ...,Measurement,137,0,0,0,137
17,46235794,Respiratory syncytial virus RNA [Presence] in ...,Measurement,133,0,0,0,133
18,1175203,Rhinovirus RNA [Presence] in Lower respiratory...,Measurement,126,0,0,0,126
19,36303355,Human coronavirus RNA [Presence] in Lower resp...,Measurement,126,0,0,0,126
20,36304988,Human coronavirus RNA [Presence] in Upper resp...,Measurement,125,0,0,0,125
21,36304562,Pneumocystis jiroveci DNA [Presence] in Lower ...,Measurement,103,0,0,0,103
22,37019853,Mycoplasma pneumoniae DNA [Presence] in Respir...,Measurement,99,0,0,0,99
23,3035167,Continuous positive airway pressure Respirator...,Measurement,19,0,0,0,19
24,36305727,Minimum expiratory pressure Respiratory system...,Measurement,10,0,0,0,10
25,4306074,Respiratory tract procedure,Procedure,0,1450,0,0,1450
26,4306073,Operation on respiratory tract,Procedure,0,55,0,0,55
27,46271394,Assessment of respiratory status using monitor...,Procedure,0,51,0,0,51
28,4006318,"Respiratory assist, manual",Procedure,0,11,0,0,11
29,4297085,Respiratory tract evaluation,Procedure,0,10,0,0,10
30,4031059,Operation on upper respiratory tract,Procedure,0,6,0,0,6
31,4259231,Respiratory function management,Observation,0,0,7718,0,7718
32,44783658,Cardiorespiratory arrest with successful resus...,Condition,0,0,0,1045,1045
33,320136,Disorder of respiratory system,Condition,0,0,0,889,889
34,4256228,Respiratory failure,Condition,0,0,0,684,684
35,4170143,Respiratory tract infection,Condition,0,0,0,481,481
36,4112341,Acute respiratory infections,Condition,0,0,0,463,463
37,252280,Neoplasm of respiratory tract,Condition,0,0,0,146,146
38,4286507,Upper respiratory tract obstruction,Condition,0,0,0,132,132
39,317109,Respiratory arrest,Condition,0,0,0,66,66

#### Explore Peep Concepts

In [21]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE lower(concept_name) LIKE '%peep%'
"""

peep_concept_df = client.query(query).to_dataframe()

peep_concept_df

    concept_id                                       concept_name    domain_id
0     45771559                               PEEP valve, reusable       Device
1     45758300                             PEEP valve, single-use       Device
2     37025932                             Intrinsic dynamic PEEP  Observation
3     37065391                                 Total dynamic PEEP  Observation
4     37028469                                     Extrinsic PEEP  Observation
5     37062926                             Extrinsic dynamic PEEP  Observation
6     37076032                                               PEEP  Observation
7     37047538                                         Total PEEP  Observation
8     37057099  Intrinsic dynamic PEEP | Respiratory system | ...  Measurement
9     37030304  Total dynamic PEEP | Respiratory system | Resp...  Measurement
10    37047691  Extrinsic dynamic PEEP | Respiratory system | ...  Measurement
11    37022872  Extrinsic PEEP | Respiratory system | Respirat...  Measurement
12    37075680  PEEP | Respiratory system | Respiratory measur...  Measurement
13    37037082  Total PEEP | Respiratory system | Respiratory ...  Measurement
14    35835625  alcohol .7mL/mL TOPICAL GEL [peeps cotton cand...         Drug
15    35835036  PEEPS VANILLA MARSHMALLOW SCREME HAND SANITIZE...         Drug
16    21490855            PEEP Respiratory system --on ventilator  Measurement
17    41887777                                          Peep Hill    Geography
18    42528516          Extrinsic dynamic PEEP Respiratory system  Measurement
19    42527139          Intrinsic dynamic PEEP Respiratory system  Measurement
20    42527140                      Total PEEP Respiratory system  Measurement
21    42528517              Total dynamic PEEP Respiratory system  Measurement
22    42528515                  Extrinsic PEEP Respiratory system  Measurement
23     3016226                            PEEP Respiratory system  Measurement
24     3021559              Minimum PEEP setting Ventilator alarm  Measurement
25     3035822                  Intrinsic PEEP Respiratory system  Measurement
26     1980497  alcohol .7mL/mL TOPICAL GEL [peeps cotton cand...         Drug
27     4276747                                      Spring peeper  Observation
28     4072522  Positive end expiratory pressure increased to ...    Procedure
29     4074669  Positive end expiratory pressure reduced to op...    Procedure
30     4023301                                        Peeping Tom  Observation
31     4072523  Positive end expiratory pressure reduced to be...    Procedure
32     4072518  Positive end expiratory pressure increased to ...    Procedure

### Peep Visit Count

In [22]:
query = f"""
WITH peep AS (
    SELECT concept_id, concept_name, domain_id
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
    WHERE LOWER(concept_name) LIKE '%peep%'
)
SELECT
    p.concept_id,
    p.concept_name,
    p.domain_id,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
      WHERE measurement_concept_id = p.concept_id AND provider_id IS NOT NULL)                           AS meas_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.device_exposure`
      WHERE device_concept_id = p.concept_id AND provider_id IS NOT NULL)     AS device_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.observation`
      WHERE observation_concept_id = p.concept_id AND provider_id IS NOT NULL)                           AS obs_visits
FROM peep p
ORDER BY meas_visits DESC, device_visits DESC
"""
peep_concept_df = client.query(query).to_dataframe()
peep_concept_df['total_visits'] = peep_concept_df[['meas_visits','device_visits','obs_visits']].sum(axis=1)
print(f"Concepts matching 'peep': {len(peep_concept_df)}")
print(f"With any data: {(peep_concept_df['total_visits'] > 0).sum()}")
peep_concept_df

Concepts matching 'peep': 33
With any data: 3

,concept_id,concept_name,domain_id,meas_visits,device_visits,obs_visits,total_visits
0,21490855,PEEP Respiratory system --on ventilator,Measurement,16431,0,0,16431
1,42527140,Total PEEP Respiratory system,Measurement,1774,0,0,1774
2,3035822,Intrinsic PEEP Respiratory system,Measurement,148,0,0,148
3,37022872,Extrinsic PEEP | Respiratory system | Respirat...,Measurement,0,0,0,0
4,45758300,"PEEP valve, single-use",Device,0,0,0,0
5,37076032,PEEP,Observation,0,0,0,0
6,37047691,Extrinsic dynamic PEEP | Respiratory system | ...,Measurement,0,0,0,0
7,42528516,Extrinsic dynamic PEEP Respiratory system,Measurement,0,0,0,0
8,37037082,Total PEEP | Respiratory system | Respiratory ...,Measurement,0,0,0,0
9,42528517,Total dynamic PEEP Respiratory system,Measurement,0,0,0,0
10,41887777,Peep Hill,Geography,0,0,0,0
11,42528515,Extrinsic PEEP Respiratory system,Measurement,0,0,0,0
12,4023301,Peeping Tom,Observation,0,0,0,0
13,37047538,Total PEEP,Observation,0,0,0,0
14,3016226,PEEP Respiratory system,Measurement,0,0,0,0
15,45771559,"PEEP valve, reusable",Device,0,0,0,0
16,37065391,Total dynamic PEEP,Observation,0,0,0,0
17,35835625,alcohol .7mL/mL TOPICAL GEL [peeps cotton cand...,Drug,0,0,0,0
18,4074669,Positive end expiratory pressure reduced to op...,Procedure,0,0,0,0
19,1980497,alcohol .7mL/mL TOPICAL GEL [peeps cotton cand...,Drug,0,0,0,0
20,37057099,Intrinsic dynamic PEEP | Respiratory system | ...,Measurement,0,0,0,0
21,4072523,Positive end expiratory pressure reduced to be...,Procedure,0,0,0,0
22,3021559,Minimum PEEP setting Ventilator alarm,Measurement,0,0,0,0
23,4072522,Positive end expiratory pressure increased to ...,Procedure,0,0,0,0
24,4276747,Spring peeper,Observation,0,0,0,0
25,35835036,PEEPS VANILLA MARSHMALLOW SCREME HAND SANITIZE...,Drug,0,0,0,0
26,37030304,Total dynamic PEEP | Respiratory system | Resp...,Measurement,0,0,0,0
27,4072518,Positive end expiratory pressure increased to ...,Procedure,0,0,0,0
28,42527139,Intrinsic dynamic PEEP Respiratory system,Measurement,0,0,0,0
29,37025932,Intrinsic dynamic PEEP,Observation,0,0,0,0
30,37062926,Extrinsic dynamic PEEP,Observation,0,0,0,0
31,37075680,PEEP | Respiratory system | Respiratory measur...,Measurement,0,0,0,0
32,37028469,Extrinsic PEEP,Observation,0,0,0,0

#### Explore Mechanical Ventilation Concepts

In [23]:
query = f"""
SELECT concept_id, concept_name, domain_id
FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
WHERE lower(concept_name) LIKE '%mechanical ventilation%'
"""

mechanical_ventilation_concept_df = client.query(query).to_dataframe()

mechanical_ventilation_concept_df

    concept_id                                       concept_name    domain_id
0     37158404                    Invasive mechanical ventilation    Procedure
1     42530690  Invasive mechanical ventilation by intubation ...   Meas Value
2     42527120  Expired minute Volume during Mechanical ventil...  Measurement
3     42527121  Inspired minute Volume during Mechanical venti...  Measurement
4      1035133  Yes, on invasive mechanical ventilation suppor...   Meas Value
5      1620591  Hospitalized - severe disease, intubation and ...   Meas Value
6      1017310  Invasive mechanical ventilation support upon a...  Observation
7       801179  Injection, tocilizumab, for hospitalized adult...         Drug
8       801187  Intravenous infusion, tocilizumab, for hospita...         Drug
9       801188  Intravenous infusion, tocilizumab, for hospita...         Drug
10    36308727  Not fully liberated at discharge (i.e., patien...   Meas Value
11    36308277  Fully liberated at discharge (i.e., patient di...   Meas Value
12    36308558  No, not on invasive mechanical ventilation sup...   Meas Value
13    36308817  Respiratory assistance with manual or mechanic...   Meas Value
14    36305051  Invasive mechanical ventilation support upon a...  Observation
15    36034360  Whether the patient received mechanical ventil...  Observation
16    36033371  Whether the patient received mechanical ventil...  Measurement
17    36031207  Whether the patient received mechanical ventil...  Observation
18     2008006   Other continuous invasive mechanical ventilation    Procedure
19     2008007  Continuous invasive mechanical ventilation of ...    Procedure
20     2008009  Continuous invasive mechanical ventilation for...    Procedure
21     2008008  Continuous invasive mechanical ventilation for...    Procedure
22     2007680                Non-invasive mechanical ventilation    Procedure
23     2614873  Moisture exchanger, disposable, for use with i...       Device
24    40461915                             Mechanical ventilation    Procedure
25    40312603  Mechanical ventilation (& intermittent positiv...    Procedure
26    40378385  Mechanical ventilation (& intermittent positiv...    Procedure
27     4232550         Home visit for mechanical ventilation care  Observation
28     4332501   Management of noninvasive mechanical ventilation    Procedure
29     4232891                    Mechanical ventilation response  Observation
30     4229714            Mechanical ventilation weaning response  Observation

### Mechanical Ventillation Visit Count

In [24]:
query = f"""
WITH mv AS (
    SELECT concept_id, concept_name, domain_id
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept`
    WHERE LOWER(concept_name) LIKE '%mechanical ventilation%'
)
SELECT
    m.concept_id,
    m.concept_name,
    m.domain_id,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.procedure_occurrence`
      WHERE procedure_concept_id = m.concept_id AND provider_id IS NOT NULL)  AS proc_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
      WHERE measurement_concept_id = m.concept_id AND provider_id IS NOT NULL)                           AS meas_visits,
    (SELECT COUNT(DISTINCT visit_occurrence_id)
       FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.observation`
      WHERE observation_concept_id = m.concept_id AND provider_id IS NOT NULL)                           AS obs_visits
FROM mv m
ORDER BY proc_visits DESC, meas_visits DESC, obs_visits DESC
"""
mechanical_ventilation_concept_df = client.query(query).to_dataframe()
mechanical_ventilation_concept_df['total_visits'] = mechanical_ventilation_concept_df[['proc_visits','meas_visits','obs_visits']].sum(axis=1)
print(f"Concepts matching 'mechanical ventilation': {len(mechanical_ventilation_concept_df)}")
print(f"With any data: {(mechanical_ventilation_concept_df['total_visits'] > 0).sum()}")
mechanical_ventilation_concept_df

Concepts matching 'mechanical ventilation': 31
With any data: 2

,concept_id,concept_name,domain_id,proc_visits,meas_visits,obs_visits,total_visits
0,42527120,Expired minute Volume during Mechanical ventil...,Measurement,0,15538,0,15538
1,42527121,Inspired minute Volume during Mechanical venti...,Measurement,0,15512,0,15512
2,36308558,"No, not on invasive mechanical ventilation sup...",Meas Value,0,0,0,0
3,2614873,"Moisture exchanger, disposable, for use with i...",Device,0,0,0,0
4,1035133,"Yes, on invasive mechanical ventilation suppor...",Meas Value,0,0,0,0
5,37158404,Invasive mechanical ventilation,Procedure,0,0,0,0
6,40312603,Mechanical ventilation (& intermittent positiv...,Procedure,0,0,0,0
7,1017310,Invasive mechanical ventilation support upon a...,Observation,0,0,0,0
8,1620591,"Hospitalized - severe disease, intubation and ...",Meas Value,0,0,0,0
9,36034360,Whether the patient received mechanical ventil...,Observation,0,0,0,0
10,36305051,Invasive mechanical ventilation support upon a...,Observation,0,0,0,0
11,2008006,Other continuous invasive mechanical ventilation,Procedure,0,0,0,0
12,40461915,Mechanical ventilation,Procedure,0,0,0,0
13,42530690,Invasive mechanical ventilation by intubation ...,Meas Value,0,0,0,0
14,36308817,Respiratory assistance with manual or mechanic...,Meas Value,0,0,0,0
15,2008009,Continuous invasive mechanical ventilation for...,Procedure,0,0,0,0
16,36031207,Whether the patient received mechanical ventil...,Observation,0,0,0,0
17,36308727,"Not fully liberated at discharge (i.e., patien...",Meas Value,0,0,0,0
18,4232891,Mechanical ventilation response,Observation,0,0,0,0
19,801188,"Intravenous infusion, tocilizumab, for hospita...",Drug,0,0,0,0
20,40378385,Mechanical ventilation (& intermittent positiv...,Procedure,0,0,0,0
21,36033371,Whether the patient received mechanical ventil...,Measurement,0,0,0,0
22,2007680,Non-invasive mechanical ventilation,Procedure,0,0,0,0
23,2008008,Continuous invasive mechanical ventilation for...,Procedure,0,0,0,0
24,4332501,Management of noninvasive mechanical ventilation,Procedure,0,0,0,0
25,4232550,Home visit for mechanical ventilation care,Observation,0,0,0,0
26,801187,"Intravenous infusion, tocilizumab, for hospita...",Drug,0,0,0,0
27,4229714,Mechanical ventilation weaning response,Observation,0,0,0,0
28,2008007,Continuous invasive mechanical ventilation of ...,Procedure,0,0,0,0
29,36308277,"Fully liberated at discharge (i.e., patient di...",Meas Value,0,0,0,0
30,801179,"Injection, tocilizumab, for hospitalized adult...",Drug,0,0,0,0

### Validate candidate feature concepts ([Zappalà et al. predictors ](https://www.sciencedirect.com/science/article/pii/S0883944125000929))

AI-assisted (Claude, Anthropic — Claude Opus 4.8): predictor-to-concept search with visit validation drafted with AI.

In [25]:
# Candidate feature concepts from Zappalà et al. predictor variables.
# Each term searched + visit-counted across the domains it could live in.

predictors = {
    'heart_rate':        ['%heart rate%'],
    'blood_pressure':    ['%arterial blood pressure%', '%mean blood pressure%'],
    'respiratory_rate':  ['%respiratory rate%'],
    'spo2':              ['%oxygen saturation%', '%spo2%'],
    'fio2':              ['%fio2%', '%inspired oxygen%'],
    'peep':              ['%peep%'],
    'tidal_volume':      ['%tidal volume%'],
    'plateau_pressure':  ['%plateau pressure%'],
    'pao2':              ['%pao2%', '%oxygen [partial pressure] in arterial%'],
    'paco2':             ['%paco2%', '%carbon dioxide [partial pressure] in arterial%'],
    'ph':                ['%ph of arterial blood%'],
    'lactate':           ['%lactate%'],
    'sedation_score':    ['%sedation%', '%richmond%', '%rass%'],
    'weight':            ['%body weight%'],
}

rows = []
for feat, terms in predictors.items():
    like = ' OR '.join([f"LOWER(c.concept_name) LIKE '{t}'" for t in terms])
    query = f"""
    SELECT c.concept_id, c.concept_name, c.domain_id,
           (SELECT COUNT(DISTINCT visit_occurrence_id)
              FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.measurement`
             WHERE measurement_concept_id = c.concept_id AND provider_id IS NOT NULL) AS meas_visits
    FROM `{DATASET_PROJECT_ID}.{DATASET_ID}.concept` c
    WHERE ({like}) AND c.standard_concept = 'S'
    ORDER BY meas_visits DESC
    LIMIT 3
    """
    df = client.query(query).to_dataframe()
    df.insert(0, 'feature', feat)
    rows.append(df)

candidate_features = pd.concat(rows, ignore_index=True)
print(candidate_features.to_string(index=False))

         feature  concept_id                                                                                                                                                                                                                                         concept_name   domain_id  meas_visits
      heart_rate    21490872                                                                                                                                                                                                                       Heart rate.beat-to-beat by EKG Measurement        23041
      heart_rate     3027018                                                                                                                                                                                                                                           Heart rate Measurement          447
      heart_rate     3019995                                                                                                                                                                                                       Heart rate device Institution inventory number Measurement            0
  blood_pressure    21490852                                                                                                                                                                                                                         Invasive Mean blood pressure Measurement        21561
  blood_pressure    21492241                                                                                                                                                                                                                   Mean blood pressure by Noninvasive Measurement        10612
  blood_pressure     3028074                                                                                                                                                                                                                 Pulmonary artery Mean blood pressure Measurement         7741
respiratory_rate     3024171                                                                                                                                                                                                                                     Respiratory rate Measurement        21962
respiratory_rate     3013606                                                                                                                                                                                                                 Respiratory rate --post bronchoscopy Measurement            0
respiratory_rate     3021375                                                                                                                                                                                                                  Respiratory rate --pre bronchoscopy Measurement            0
            spo2    40762499                                                                                                                                                                                                Oxygen saturation in Arterial blood by Pulse oximetry Measurement        22978
            spo2    42869608                                                                                                                                                                                                      Oxygen saturation [Pure mass fraction] in Blood Measurement        22414
            spo2     3018465                                                                                                                                                                                                              Oxygen saturation in Mixed venous blood Measurement           58
            fio2    45762347                                                                                                                                                                                         Enclosed-atmosphere inspired oxygen monitor, battery-powered      Device            0
            fio2      608618                                                                                                                                                                              NPEWS (National Paediatric Early Warning Score) - inspired oxygen score Measurement            0
            fio2    45877565                                                                                                                                                                                                High O2 Concentration Delivery System with FiO2 > 40%  Meas Value            0
            peep    21490855                                                                                                                                                                                                              PEEP Respiratory system --on ventilator Measurement        16431
            peep    42527140                                                                                                                                                                                                                        Total PEEP Respiratory system Measurement         1774
            peep     3035822                                                                                                                                                                                                                    Intrinsic PEEP Respiratory system Measurement          148
    tidal_volume     3016166                                                                                                                                                                                Tidal volume inspired spontaneous+mechanical Measured --on ventilator Measurement        15536
    tidal_volume     3015016                                                                                                                                                                Tidal volume expired spontaneous+mechanical Respiratory system airway --on ventilator Measurement        15527
    tidal_volume     3012410                                                                                                                                                                                                                      Tidal volume setting Ventilator Measurement         6853
plateau_pressure     3036889                                                                                                                                                          Tidal volume expired/Plateau pressure --post 1.5-2.0 seconds inspiratory hold on ventilator Measurement            0
plateau_pressure    21490565                                                                                                                                                                                                                             Dynamic plateau pressure Measurement            0
plateau_pressure     4139635                                                                                                                                                                                                                                     Plateau pressure Observation            0
            pao2     3027801                                                                                                                                                                                                          Oxygen [Partial pressure] in Arterial blood Measurement            0
            pao2     3021706                                                                                                                                                                                                     Oxygen [Partial pressure] in Arterial cord blood Measurement            0
           paco2     3027946                                                                                                                                                                                                  Carbon dioxide [Partial pressure] in Arterial blood Measurement            0
           paco2     3003932                                                                                                                                                                                             Carbon dioxide [Partial pressure] in Arterial cord blood Measurement            0
              ph     3029473                                                                                                                                                                                        pH of Arterial blood adjusted to patient's actual temperature Measurement            0
              ph     3019977                                                                                                                                                                                                                                 pH of Arterial blood Measurement            0
         lactate     3047181                                                                                                                                                                                                                      Lactate [Moles/volume] in Blood Measurement        17330
         lactate     3016436                                                                                                                                                                                 Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma Measurement        17121
         lactate     3014111                                                                                                                                                                                                            Lactate [Moles/volume] in Serum or Plasma Measurement          342
  sedation_score     4105091                                                                                                                                                                                                                                Ramsay sedation scale Measurement        11173
  sedation_score    36684829                                                                                                                                                                                                                    Richmond Agitation-Sedation Scale Measurement         5000
  sedation_score    43859053 annual bluegrass pollen extract 14.3 UNT/ML / cultivated oat pollen extract 14.3 UNT/ML / cultivated rye grass pollen extract 14.3 UNT/ML / meadow fescue grass pollen extract 28.6 UNT/ML / Timothy grass pollen extract 14.3 UNT/ML [Alk-Depot Sq]        Drug            0
          weight    37206608                                                                                                                                                                                                                      Self reported usual body weight Measurement           19
          weight     3014618                                                                                                                                                               Fetal Body weight estimated from Abdominal circumference on US by Campbell 1975 method Measurement            0
          weight     3026659                                                                                                                                                                                                                            Dry body weight Estimated Measurement            0

heart rate, blood pressure, respiratory rate, SpO_2, PEEP, tidal volume, lactate, sedation score are well recorded and ready to use some concepts showing no data need to modify the search term.